name: caribpay
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  toastification: ^3.0.2
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  getwidget: ^6.0.0
  phosphor_flutter: ^2.1.0
  fluentui_system_icons: ^1.1.271
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  dio: ^5.8.0+1
  logger: ^2.5.0
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
